//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSwitch.CustomerTools.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoSwitchProductionNewEntities : DbContext
    {
        public GoSwitchProductionNewEntities()
            : base("name=GoSwitchProductionNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<NewCampaignCode> NewCampaignCodes { get; set; }
        public virtual DbSet<NewCustomer> NewCustomers { get; set; }
        public virtual DbSet<NewDistributor> NewDistributors { get; set; }
        public virtual DbSet<NewEnergyType> NewEnergyTypes { get; set; }
        public virtual DbSet<NewPresale> NewPresales { get; set; }
        public virtual DbSet<NewRetailer> NewRetailers { get; set; }
        public virtual DbSet<NewSaleType> NewSaleTypes { get; set; }
        public virtual DbSet<NewState> NewStates { get; set; }
        public virtual DbSet<NewTitle> NewTitles { get; set; }
        public virtual DbSet<NewUsage> NewUsages { get; set; }
    }
}
