//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSwitch.CustomerTools.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCustomer
    {
        public int CustomerID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ZipCode { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Address { get; set; }
        public string FullAddress { get; set; }
        public string CustomerType { get; set; }
        public string CompanyName { get; set; }
        public string ABN { get; set; }
        public string NMI { get; set; }
        public string MIRN { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string UnitNumber { get; set; }
        public string StreetNumber { get; set; }
        public string StreetType { get; set; }
        public Nullable<int> IDType { get; set; }
        public string IDNumber { get; set; }
        public Nullable<bool> IsConcession { get; set; }
        public Nullable<bool> PrinciplePlaceOfResidence { get; set; }
        public Nullable<int> ConcessionIssuerID { get; set; }
        public Nullable<int> ConcessionTypeID { get; set; }
        public string ConcessionCardNumber { get; set; }
        public Nullable<System.DateTime> ConcessionStartDate { get; set; }
        public Nullable<System.DateTime> ConcessionExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
