//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSwitch.CustomerTools.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewRetailer
    {
        public int RetailerID { get; set; }
        public string RetailerName { get; set; }
        public string ResEmail { get; set; }
        public string ResCCEmail { get; set; }
        public string SMEEmail { get; set; }
        public string SMECCEmail { get; set; }
        public Nullable<bool> UseFTP { get; set; }
        public string ftpHostIP { get; set; }
        public string ftpUserName { get; set; }
        public string ftpPassword { get; set; }
        public Nullable<bool> GetLead { get; set; }
        public Nullable<bool> IsEncrypted { get; set; }
        public string EncryptionPassword { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> GreenEnergyAdditionCost { get; set; }
        public bool IsContracted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
