//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSwitch.CustomerTools.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewSaleType
    {
        public int SaleTypeID { get; set; }
        public string SaleTypeCode { get; set; }
        public string SaleTypeName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
