//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSwitch.CustomerTools.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewUsage
    {
        public int UsageID { get; set; }
        public string CustomerType { get; set; }
        public int EnergyTypeID { get; set; }
        public int BillCycleID { get; set; }
        public int StateID { get; set; }
        public string UsageLevel { get; set; }
        public string UsageSize { get; set; }
        public double UsageValue { get; set; }
        public bool isActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
